### ISSUE TITLE
What does "No support for subdir base url" mean?

### ISSUE THREAD

**Issue by salcc** [salif/zola-themes-collection#1]
I am the developer of the bearplus theme and I see that it's listed under non-elegible thems because "No support for subdir base url". What does this mean?

I'm not sure if it's referring to this, but note that until recently, the theme demo used a subdirectory (salcc.github.com/zola-bearplus) as a `base_url` (https://github.com/salcc/zola-bearplus/compare/14becb9..49c5557). Some days ago I started using a custom domain for my personal webpage and now the demo is hosted in the subdomain https://theme.marçal.cc, but using a subdirectory for `base_url` like before still works correctly.

**Comment by salif** [comment]
Hi. Your theme uses absolute path for css files: `href="/style.css"`.

I am using the following `base_url` addresses:
```
http://127.0.0.1:1111/demo/bearplus/
https://salif.github.io/zola-themes-collection/demo/bearplus/
```
As a result, `style.css` is located at the following addresses:
```
http://127.0.0.1:1111/demo/bearplus/style.css
https://salif.github.io/zola-themes-collection/demo/bearplus/style.css
```
But your theme expects `style.css` to be located at the following addresses:
```
http://127.0.0.1:1111/style.css
https://salif.github.io/style.css
```

**Comment by salcc** [comment]
Thanks for the explanation. I fixed it now.

**Comment by salif** [comment]
Thanks. I added bearplus in 38b4313c71cd3a6c03fbe085f3fafe3e7462ff62.

**Comment by salif** [comment]
@salcc Hello. What happened with the bearplus theme? Should I remove it?
